force-app/main/default/objects/Reciept__c/Reciept__c.object-meta.xml
<CustomObject>
    <label>Receipt</label>
    <nameField>
        <label>Reciept Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Receipts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Reciept__c/fields/ValletId__c.field-meta.xml
<CustomField>
    <fullName>ValletId__c</fullName>
    <label>Vallet</label>
    <referenceTo>Wallet__c</referenceTo>
    <relationshipLabel>Receipts</relationshipLabel>
    <relationshipName>Receipts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Wallet__c/Wallet__c.object-meta.xml
<CustomObject>
    <label>Wallet</label>
    <nameField>
        <label>Wallet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wallets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/FinGuardChangeReceiptController.cls
/**
 * Created by aleksejuporojskij on 12/20/19.
 */

public with sharing class FinGuardChangeReceiptController {
    @AuraEnabled
    public static void updateReceipt (Reciept__c newReceipt, string wallet) {
        if(wallet!=''){
            Wallet__c selectWallet =   [SELECT Name
            FROM Wallet__c
            WHERE Name =:wallet];
            newReceipt.ValletId__c =selectWallet.Id;
        }

        if (newReceipt != null) {
            update newReceipt;
        }
    }
    @AuraEnabled
    public static void deleteSelectedReceipt (string receiptToDeleteId) {
        Reciept__c receiptToDelete =   [SELECT Name
        FROM Reciept__c
        WHERE Id =:receiptToDeleteId];

        delete receiptToDelete;

    }

}