force-app/main/default/objects/Reciept__c/Reciept__c.object-meta.xml
<CustomObject>
    <label>Receipt</label>
    <nameField>
        <label>Reciept Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Receipts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Reciept__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Зарплата</fullName>
            </value>
            <value>
                <fullName>Детские</fullName>
            </value>
            <value>
                <fullName>Обмен валюты</fullName>
            </value>
            <value>
                <fullName>Подарок</fullName>
            </value>
            <value>
                <fullName>Коррекция+</fullName>
            </value>
            <value>
                <fullName>Другие</fullName>
            </value>
            <value>
                <fullName>Ревизия</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reciept__c/fields/Receipt_Date__c.field-meta.xml
<CustomField>
    <fullName>Receipt_Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Receipt_Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reciept__c/fields/ValletId__c.field-meta.xml
<CustomField>
    <fullName>ValletId__c</fullName>
    <label>Vallet</label>
    <referenceTo>Wallet__c</referenceTo>
    <relationshipLabel>Receipts</relationshipLabel>
    <relationshipName>Receipts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Wallet__c/Wallet__c.object-meta.xml
<CustomObject>
    <label>Wallet</label>
    <nameField>
        <label>Wallet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wallets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/FinGuardViewReceiptsController.cls
/**
 * Created by Алексей on 10.12.2019.
 */

public with sharing class FinGuardViewReceiptsController {
    @AuraEnabled(cacheable=true)
    public static List<Reciept__c> getReceiptsList () {
        List <Reciept__c> getReceipts = [
                SELECT  Name,
                        Value__c,
                        Category__c,
                        Receipt_Date__c,
                        ValletId__r.Name

                FROM    Reciept__c
                ORDER BY Receipt_Date__c
                        DESC                    ];
        return  getReceipts;



    }
}