force-app/main/default/objects/Wallet__c/Wallet__c.object-meta.xml
<CustomObject>
    <label>Wallet</label>
    <nameField>
        <label>Wallet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wallets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Wallet__c/fields/Balance__c.field-meta.xml
<CustomField>
    <fullName>Balance__c</fullName>
    <formula>Total_Receipts__c - Total_Expenses__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Wallet__c/fields/Monetary_Unit__c.field-meta.xml
<CustomField>
    <fullName>Monetary_Unit__c</fullName>
    <label>Monetary_Unit</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Wallet__c/fields/Total_Expenses__c.field-meta.xml
<CustomField>
    <fullName>Total_Expenses__c</fullName>
    <label>Total_Expenses</label>
    <summarizedField>Expense__c.Value__c</summarizedField>
    <summaryForeignKey>Expense__c.ValletId__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Wallet__c/fields/Total_Receipts__c.field-meta.xml
<CustomField>
    <fullName>Total_Receipts__c</fullName>
    <label>Total_Receipts</label>
    <summarizedField>Reciept__c.Value__c</summarizedField>
    <summaryForeignKey>Reciept__c.ValletId__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/FinGuardWalletsController.cls
public with sharing class FinGuardWalletsController {
        @AuraEnabled
        public static List<Wallet__c> getWalletsList () {
                List <Wallet__c> getWallets = [
                    SELECT  Name, Balance__c, Total_Expenses__c, Total_Receipts__c, Monetary_Unit__c, Currency__c, CreatedDate
                    FROM    Wallet__c
                ];
                return  getWallets;



        }

    }