force-app/main/default/objects/Car__c/Car__c.object-meta.xml
<CustomObject>
    <label>Car</label>
    <nameField>
        <label>Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Car__c/fields/Consumption__c.field-meta.xml
<CustomField>
    <fullName>Consumption__c</fullName>
    <formula>TotalFuel__c/ TotalKm__c *100</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Consumption</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/TotalFuel__c.field-meta.xml
<CustomField>
    <fullName>TotalFuel__c</fullName>
    <label>TotalFuel</label>
    <summarizedField>FuelLoad__c.Amount__c</summarizedField>
    <summaryForeignKey>FuelLoad__c.CarId__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/TotalKm__c.field-meta.xml
<CustomField>
    <fullName>TotalKm__c</fullName>
    <label>TotalKm</label>
    <summarizedField>KmPerDay__c.Amount__c</summarizedField>
    <summaryForeignKey>KmPerDay__c.CarId__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <label>Expense</label>
    <nameField>
        <label>Expense Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Продукты</fullName>
            </value>
            <value>
                <fullName>Непродуктовые</fullName>
            </value>
            <value>
                <fullName>Коммунальные</fullName>
            </value>
            <value>
                <fullName>Связь</fullName>
            </value>
            <value>
                <fullName>Одежда</fullName>
            </value>
            <value>
                <fullName>Здоровье</fullName>
            </value>
            <value>
                <fullName>Развлечения</fullName>
            </value>
            <value>
                <fullName>Образование</fullName>
            </value>
            <value>
                <fullName>Авто</fullName>
            </value>
            <value>
                <fullName>Транспорт</fullName>
            </value>
            <value>
                <fullName>Обмен валюты</fullName>
            </value>
            <value>
                <fullName>Другие</fullName>
            </value>
            <value>
                <fullName>Коррекция-</fullName>
            </value>
            <value>
                <fullName>Проекты</fullName>
            </value>
            <value>
                <fullName>Услуги</fullName>
            </value>
            <value>
                <fullName>Ревизия</fullName>
            </value>
            <value>
                <fullName>Недвижимость</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Expense_Date__c.field-meta.xml
<CustomField>
    <fullName>Expense_Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Expense Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Value</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CarInfoSummaryController.cls
public with sharing class CarInfoSummaryController {
    @AuraEnabled
    public static wrapper getCar() {
        Wrapper wrapper = new Wrapper();
        Car__c car = [
            SELECT TotalFuel__c,TotalKm__c,Consumption__c,CreatedDate
        	FROM Car__c
        	LIMIT 1];
        DateTime createdCarDT = car.CreatedDate;
        Date createdCar = date.newinstance(createdCarDT.year(), createdCarDT.month(), createdCarDT.day());
        List<Expense__c> CarExpenses = [
            SELECT Value__c,Expense_Date__c
            FROM Expense__c
            WHERE Category__c = 'Авто'
            AND Expense_Date__c>=:createdCar
        ];
        Decimal carExpensesSumm = 0;
		for(Expense__c carExpense : CarExpenses){
           carExpensesSumm+= carExpense.Value__c;
        }
        
        wrapper.car = car;
        wrapper.carExpensesSumm = carExpensesSumm;
    return wrapper;
    }
    public class Wrapper{
    	@AuraEnabled
        public Car__c car { get; set; }
        @AuraEnabled
        public Decimal carExpensesSumm { get; set; }  
    }
}