force-app/main/default/objects/CategoryOptions__mdt/CategoryOptions__mdt.object-meta.xml
<CustomObject>
    <label>Category Options</label>
    <pluralLabel>Categories Options</pluralLabel>
</CustomObject>

force-app/main/default/objects/CategoryOptions__mdt/fields/Options__c.field-meta.xml
<CustomField>
    <fullName>Options__c</fullName>
    <label>Options</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Wallet__c/Wallet__c.object-meta.xml
<CustomObject>
    <label>Wallet</label>
    <nameField>
        <label>Wallet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wallets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Wallet__c/fields/Balance__c.field-meta.xml
<CustomField>
    <fullName>Balance__c</fullName>
    <formula>Total_Receipts__c - Total_Expenses__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Wallet__c/fields/Total_Expenses__c.field-meta.xml
<CustomField>
    <fullName>Total_Expenses__c</fullName>
    <label>Total_Expenses</label>
    <summarizedField>Expense__c.Value__c</summarizedField>
    <summaryForeignKey>Expense__c.ValletId__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Wallet__c/fields/Total_Receipts__c.field-meta.xml
<CustomField>
    <fullName>Total_Receipts__c</fullName>
    <label>Total_Receipts</label>
    <summarizedField>Reciept__c.Value__c</summarizedField>
    <summaryForeignKey>Reciept__c.ValletId__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

classes/MStoreController.cls
public with sharing class MStoreController {

    @AuraEnabled
    public static List <Wallet__c> getAccounts() {
        List<Wallet__c> accounts = [
            SELECT  Name, CreatedDate, Balance__c, Currency__c, Total_Expenses__c, Total_Receipts__c
            FROM    Wallet__c
        ];
        return  accounts;
    }

    @AuraEnabled
    public static Map<String, List<String>> getCategoriesOptions() {

        Map<String, List<String>> optionsMap = new Map<String, List<String>>();
        List<CategoryOptions__mdt> options = [
            SELECT 	MasterLabel, Options__c
            FROM CategoryOptions__mdt
        ];

        for (CategoryOptions__mdt o : options) {
            List<String> optionsList = new List<String>();
            optionsList = o.Options__c.split(';');
            optionsMap.put(o.MasterLabel, optionsList);
        }
        
        return optionsMap;
    }

    @AuraEnabled
    public static Boolean saveOperations(List<SObject> operations) {
        Boolean success = true;
        List<Database.SaveResult> results = Database.insert(operations, true);
        for (Database.SaveResult r : results) {
            if (!r.isSuccess()) {
                success = false;
                break;
            }
        }
        return success;
    }
}