force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <label>Expense</label>
    <nameField>
        <label>Expense Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Продукты</fullName>
            </value>
            <value>
                <fullName>Непродуктовые</fullName>
            </value>
            <value>
                <fullName>Коммунальные</fullName>
            </value>
            <value>
                <fullName>Связь</fullName>
            </value>
            <value>
                <fullName>Одежда</fullName>
            </value>
            <value>
                <fullName>Здоровье</fullName>
            </value>
            <value>
                <fullName>Развлечения</fullName>
            </value>
            <value>
                <fullName>Образование</fullName>
            </value>
            <value>
                <fullName>Авто</fullName>
            </value>
            <value>
                <fullName>Транспорт</fullName>
            </value>
            <value>
                <fullName>Обмен валюты</fullName>
            </value>
            <value>
                <fullName>Другие</fullName>
            </value>
            <value>
                <fullName>Коррекция-</fullName>
            </value>
            <value>
                <fullName>Проекты</fullName>
            </value>
            <value>
                <fullName>Услуги</fullName>
            </value>
            <value>
                <fullName>Ревизия</fullName>
            </value>
            <value>
                <fullName>Недвижимость</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Expense_Date__c.field-meta.xml
<CustomField>
    <fullName>Expense_Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Expense Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/ValletId__c.field-meta.xml
<CustomField>
    <fullName>ValletId__c</fullName>
    <label>Vallet</label>
    <referenceTo>Wallet__c</referenceTo>
    <relationshipLabel>Expenses</relationshipLabel>
    <relationshipName>Expenses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Value</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Wallet__c/Wallet__c.object-meta.xml
<CustomObject>
    <label>Wallet</label>
    <nameField>
        <label>Wallet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wallets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/FinGuardViewExpensesController.cls
/**
 * Created by Алексей on 08.12.2019.
 */

public with sharing class FinGuardViewExpensesController {
    @AuraEnabled(cacheable=true)
    public static List<Expense__c> getExpensesList () {
        List <Expense__c> getExpenses = [
                SELECT  Name,
                        Value__c,
                        Category__c,
                        Expense_Date__c,
                        ValletId__r.Name

                FROM    Expense__c
                ORDER BY Expense_Date__c
                DESC                    ];
        return  getExpenses;



    }
}