force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <label>Expense</label>
    <nameField>
        <label>Expense Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense__c/fields/ValletId__c.field-meta.xml
<CustomField>
    <fullName>ValletId__c</fullName>
    <label>Vallet</label>
    <referenceTo>Wallet__c</referenceTo>
    <relationshipLabel>Expenses</relationshipLabel>
    <relationshipName>Expenses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Wallet__c/Wallet__c.object-meta.xml
<CustomObject>
    <label>Wallet</label>
    <nameField>
        <label>Wallet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wallets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/FinGuardChangeExpenseController.cls
/**
 * Created by aleksejuporojskij on 12/17/19.
 */

public with sharing class FinGuardChangeExpenseController {
    @AuraEnabled
    public static void updateExpense (Expense__c newExpense, string wallet) {
        if(wallet!=''){
            Wallet__c selectWallet =   [SELECT Name
                                        FROM Wallet__c
                                        WHERE Name =:wallet];
            newExpense.ValletId__c =selectWallet.Id;
        }

        if (newExpense != null) {
            update newExpense;
        }
    }
    @AuraEnabled
    public static void deleteSelectedExpense (string expenseToDeleteId) {
            Expense__c expenseToDelete =   [SELECT Name
            FROM Expense__c
            WHERE Id =:expenseToDeleteId];
        System.debug('Name of deleted expense: ' + expenseToDelete.Name);

        delete expenseToDelete;

    }
}