force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <label>Expense</label>
    <nameField>
        <label>Expense Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Value</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/FinGuardExpenseCreateController.cls
/**
 * Created by Алексей on 05.12.2019.
 */

public with sharing class FinGuardExpenseCreateController {
    @AuraEnabled
    public static void saveSelectedExpense (Expense__c newExpense) {
        System.debug('in Apex controller');
        System.debug('newExpenseName: ' + newExpense.Name);
        System.debug('newExpenseValue: ' + newExpense.Value__c);
        System.debug('newExpenseName: ' + newExpense.Name);
        if (newExpense != null) {
            insert newExpense;
        }
    }

}