force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <label>Expense</label>
    <nameField>
        <label>Expense Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Продукты</fullName>
            </value>
            <value>
                <fullName>Непродуктовые</fullName>
            </value>
            <value>
                <fullName>Коммунальные</fullName>
            </value>
            <value>
                <fullName>Связь</fullName>
            </value>
            <value>
                <fullName>Одежда</fullName>
            </value>
            <value>
                <fullName>Здоровье</fullName>
            </value>
            <value>
                <fullName>Развлечения</fullName>
            </value>
            <value>
                <fullName>Образование</fullName>
            </value>
            <value>
                <fullName>Авто</fullName>
            </value>
            <value>
                <fullName>Транспорт</fullName>
            </value>
            <value>
                <fullName>Обмен валюты</fullName>
            </value>
            <value>
                <fullName>Другие</fullName>
            </value>
            <value>
                <fullName>Коррекция-</fullName>
            </value>
            <value>
                <fullName>Проекты</fullName>
            </value>
            <value>
                <fullName>Услуги</fullName>
            </value>
            <value>
                <fullName>Ревизия</fullName>
            </value>
            <value>
                <fullName>Недвижимость</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Expense_Date__c.field-meta.xml
<CustomField>
    <fullName>Expense_Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Expense Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/ValletId__c.field-meta.xml
<CustomField>
    <fullName>ValletId__c</fullName>
    <label>Vallet</label>
    <referenceTo>Wallet__c</referenceTo>
    <relationshipLabel>Expenses</relationshipLabel>
    <relationshipName>Expenses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Value</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FuelLoad__c/FuelLoad__c.object-meta.xml
<CustomObject>
    <label>FuelLoad</label>
    <nameField>
        <label>FuelLoad Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FuelLoads</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/CarSummaryFuelLoadController.cls
public with sharing class CarSummaryFuelLoadController {
	@AuraEnabled
    public static void saveCreatedFuelLoad(FuelLoad__c newFuelLoad, Decimal price){
        System.debug(newFuelLoad);
       	if (newFuelLoad != null) {
            insert newFuelLoad;
            
            Expense__c fuelExpense = new Expense__c();
            fuelExpense.Name = 'Заправка';
            fuelExpense.Category__c = 'Авто';
            fuelExpense.Expense_Date__c = newFuelLoad.Date__c;
            fuelExpense.ValletId__c = 'a002w000001hsXDAAY';
            fuelExpense.Value__c = price;
            insert fuelExpense;
            
         }
        
    }
}