force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <label>Expense</label>
    <nameField>
        <label>Expense Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense__c/fields/ValletId__c.field-meta.xml
<CustomField>
    <fullName>ValletId__c</fullName>
    <label>Vallet</label>
    <referenceTo>Wallet__c</referenceTo>
    <relationshipLabel>Expenses</relationshipLabel>
    <relationshipName>Expenses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Wallet__c.field-meta.xml
<CustomField>
    <fullName>Wallet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Wallet</label>
    <referenceTo>Wallet__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Wallet__c/Wallet__c.object-meta.xml
<CustomObject>
    <label>Wallet</label>
    <nameField>
        <label>Wallet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wallets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/FinGuardViewProjectDetailsController.cls
/**
 * Created by aleksejuporojskij on 1/3/20.
 */

public with sharing class FinGuardViewProjectDetailsController {
    @AuraEnabled
    public static void updateValueProject(Project__c projectToUpdate) {

        if (projectToUpdate != null) {
            update projectToUpdate;
        }
    }
    @AuraEnabled
    public static void saveSelectedExpense (Expense__c newExpense, string wallet) {
        System.debug('Wallet of expense: ' + wallet);
        if(wallet!=''){
            Wallet__c selectWallet =    [SELECT Name
                                        FROM Wallet__c
                                        WHERE Id =:wallet];
            newExpense.ValletId__c = selectWallet.Id;
        }
        System.debug('in Apex controller');
        System.debug('newExpenseName: ' + newExpense.Name);
        if (newExpense != null) {
            insert newExpense;
        }
    }
}